# Generated by Django 4.2.7 on 2023-11-04 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0002_choosenrecommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choosenrecommendation",
            name="recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recommendations.recommendation",
            ),
        ),
    ]
